### ISSUE TITLE
ImportError: No module named mixins

### ISSUE THREAD

**Issue by jgardounis** [danielquinn/django-encrypted-filefield#8]
Hello, I have Django 1.8 and I have installed this app to my project, but I have hit a snag. When I try to run the server it returns the error:

from django.contrib.auth.mixins import AuthMixin
ImportError: No module named mixins

**Comment by danielquinn** [comment]
Hi @jgardounis, yeah that's a bit confusing I guess.  This is the result of you following the README which is written with modern versions of Django in mind.  Django 1.8 doesn't have the various mixins that were introduced for security later (in 1.9 I think).  These features were merged in from [django-braces](https://github.com/brack3t/django-braces) so you can use that package if you want, or roll your own rules for access in your view.

I've not given a lot of thought to 1.8, since [Django will be dropping support for it soon](https://www.djangoproject.com/download/#supported-versions), so I'd recommend that you update as soon as you can!
